drop table OMS_TO_DMS_OPSTATECHANGE;
create table OMS_TO_DMS_OPSTATECHANGE (
	EV_TIMESTAMP DATE,
	OWNER VARCHAR2(30),
	OPERATION varchar2(30),
	PHASES NUMBER(3),
	EQUIP_TYPE VARCHAR2(15),
	EQUIP_ID VARCHAR2(40),
	PROCESSED NUMBER(1)
);
drop table OMS_TO_DMS_TAGOP;
create table OMS_TO_DMS_TAGOP (
	EV_TIMESTAMP DATE,
	OWNER VARCHAR2(30),
	OPERATION varchar2(30),
	TAG_ID NUMBER(10),
	USER_TAG_ID VARCHAR2(20),
	PROCESSED NUMBER(1)
);
drop table OMS_TO_DMS_TEMPOBJ;
create table OMS_TO_DMS_TEMPOBJ (
	EV_TIMESTAMP DATE,
	OWNER VARCHAR2(30),
	OPERATION varchar2(30),
	PHASES NUMBER(3),
	EQUIP_TYPE VARCHAR2(15),
	EQUIP_ID VARCHAR2(40),
	LINE_ID VARCHAR2(40),
	NODE_ID VARCHAR2(40),
	NODE2_ID VARCHAR2(40),
	PCT_DISTANCE NUMBER(3),
	PROCESSED NUMBER(1)
);
drop table OMS_ADAPTER_SETTINGS;
create table OMS_ADAPTER_SETTINGS (
	SETTING_NAME VARCHAR2(20),
	VALUE varchar2(50),
	CONSTRAINT name_pk PRIMARY KEY (SETTING_NAME)
);
grant INSERT on OMS_TO_DMS_OPSTATECHANGE to astorm1;
-- don't forget wM permissions!
grant select on OMS_TO_DMS_OPSTATECHANGE to qscwebm;
grant select on OMS_TO_DMS_TAGOP to qscwebm;
grant select on OMS_TO_DMS_TEMPOBJ to qscwebm;
