spring:
  profiles:
    # active: usage_message (or) sender (or) receiver
    active: sender

  rabbitmq:
    host: #yours#
    username: #yours#
    password: #yours#
    exchange: hello
    queue: hello

logging:
  level:
    org: ERROR

client:
  duration: 20000
